#!/bin/bash

# allow X11 access
xhost +local:docker

# start rethinkdb
docker run \
       -d \
       -v ${PWD}/data:/data \
       -p 8080:8080 \
       --name mud-rethinkdb \
       rethinkdb:latest

# start emacs
docker run \
      -d \
      -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
      -v ${PWD}:/project \
      -e DISPLAY=unix${DISPLAY} \
      -p 18080:18080 \
      --device /dev/snd \
      --name mud-emacs \
      --link mud-rethinkdb:rethinkdb \
      cmiles74/emacs-clojure
